
POST http://localhost:3070/signup
Content-Type: application/json
{
    "firstName": "",
    "middleName": "",
    "lastName": "",
    "email": "j_frongillop@salemstate.edu",
    "password": "LongAFPassword1962",
    "username": "JFrong01",
    "roomNumber": "",
    "linkedIn": "",
    "bio": ""
}
###
GET http://localhost:3070/profiles/JFrong01
###
GET http://localhost:3070/profiles/